spring.datasource.url=jdbc:postgresql://dpg-d6g171p5pdvs73c76cng-a:5432/springboot_backend_z611
spring.datasource.username=springboot_backend_z611_user
spring.datasource.password=SBiUL4mxeG6v7YABTMTsxQp9mQ2sDUqu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true